KPS_GROUPS = {'body': [['nose'],
                       ['left_eye'],
                       ['right_eye'],
                       ['left_ear'],
                       ['right_ear'],
                       ['left_shoulder'],
                       ['right_shoulder'],
                       ['left_elbow'],
                       ['right_elbow'],
                       ['left_wrist'],
                       ['right_wrist'],
                       ['left_hip'],
                       ['right_hip'],
                       ['left_knee'],
                       ['right_knee'],
                       ['left_ankle'],
                       ['right_ankle']],
              'foot': [['left_big_toe'],
                       ['left_small_toe'],
                       ['left_heel'],
                       ['right_big_toe'],
                       ['right_small_toe'],
                       ['right_heel']],
              'face': [['face-0', 'kpt-0'],
                        ['face-1', 'kpt-1'],
                        ['face-2', 'kpt-2'],
                        ['face-3', 'kpt-3'],
                        ['face-4', 'kpt-4'],
                        ['face-5', 'kpt-5'],
                        ['face-6', 'kpt-6'],
                        ['face-7', 'kpt-7'],
                        ['face-8', 'kpt-8'],
                        ['face-9', 'kpt-9'],
                        ['face-10', 'kpt-10'],
                        ['face-11', 'kpt-11'],
                        ['face-12', 'kpt-12'],
                        ['face-13', 'kpt-13'],
                        ['face-14', 'kpt-14'],
                        ['face-15', 'kpt-15'],
                        ['face-16', 'kpt-16'],
                        ['face-17', 'kpt-17'],
                        ['face-18', 'kpt-18'],
                        ['face-19', 'kpt-19'],
                        ['face-20', 'kpt-20'],
                        ['face-21', 'kpt-21'],
                        ['face-22', 'kpt-22'],
                        ['face-23', 'kpt-23'],
                        ['face-24', 'kpt-24'],
                        ['face-25', 'kpt-25'],
                        ['face-26', 'kpt-26'],
                        ['face-27', 'kpt-27'],
                        ['face-28', 'kpt-28'],
                        ['face-29', 'kpt-29'],
                        ['face-30', 'kpt-30'],
                        ['face-31', 'kpt-31'],
                        ['face-32', 'kpt-32'],
                        ['face-33', 'kpt-33'],
                        ['face-34', 'kpt-34'],
                        ['face-35', 'kpt-35'],
                        ['face-36', 'kpt-36'],
                        ['face-37', 'kpt-37'],
                        ['face-38', 'kpt-38'],
                        ['face-39', 'kpt-39'],
                        ['face-40', 'kpt-40'],
                        ['face-41', 'kpt-41'],
                        ['face-42', 'kpt-42'],
                        ['face-43', 'kpt-43'],
                        ['face-44', 'kpt-44'],
                        ['face-45', 'kpt-45'],
                        ['face-46', 'kpt-46'],
                        ['face-47', 'kpt-47'],
                        ['face-48', 'kpt-48'],
                        ['face-49', 'kpt-49'],
                        ['face-50', 'kpt-50'],
                        ['face-51', 'kpt-51'],
                        ['face-52', 'kpt-52'],
                        ['face-53', 'kpt-53'],
                        ['face-54', 'kpt-54'],
                        ['face-55', 'kpt-55'],
                        ['face-56', 'kpt-56'],
                        ['face-57', 'kpt-57'],
                        ['face-58', 'kpt-58'],
                        ['face-59', 'kpt-59'],
                        ['face-60', 'kpt-60'],
                        ['face-61', 'kpt-61'],
                        ['face-62', 'kpt-62'],
                        ['face-63', 'kpt-63'],
                        ['face-64', 'kpt-64'],
                        ['face-65', 'kpt-65'],
                        ['face-66', 'kpt-66'],
                        ['face-67', 'kpt-67']],
              'hand': [['left_hand_root'],
                       ['left_thumb1'],
                       ['left_thumb2'],
                       ['left_thumb3'],
                       ['left_thumb4'],
                       ['left_forefinger1'],
                       ['left_forefinger2'],
                       ['left_forefinger3'],
                       ['left_forefinger4'],
                       ['left_middle_finger1'],
                       ['left_middle_finger2'],
                       ['left_middle_finger3'],
                       ['left_middle_finger4'],
                       ['left_ring_finger1'],
                       ['left_ring_finger2'],
                       ['left_ring_finger3'],
                       ['left_ring_finger4'],
                       ['left_pinky_finger1'],
                       ['left_pinky_finger2'],
                       ['left_pinky_finger3'],
                       ['left_pinky_finger4'],
                       ['right_hand_root'],
                       ['right_thumb1'],
                       ['right_thumb2'],
                       ['right_thumb3'],
                       ['right_thumb4'],
                       ['right_forefinger1'],
                       ['right_forefinger2'],
                       ['right_forefinger3'],
                       ['right_forefinger4'],
                       ['right_middle_finger1'],
                       ['right_middle_finger2'],
                       ['right_middle_finger3'],
                       ['right_middle_finger4'],
                       ['right_ring_finger1'],
                       ['right_ring_finger2'],
                       ['right_ring_finger3'],
                       ['right_ring_finger4'],
                       ['right_pinky_finger1'],
                       ['right_pinky_finger2'],
                       ['right_pinky_finger3'],
                       ['right_pinky_finger4']]}
