# Found by `https://github.com/hysts/anime-face-detector`
pose_config: ckpt/hrnetv2.py
pose_ckpt: ckpt/mmpose_anime-face_hrnetv2.pth

det_config: ckpt/faster-rcnn.py
det_checkpoint: ckpt/mmdet_anime-face_faster-rcnn.pth

kps: 28

output_size: 512