# Found by `mim search mmdet  --dataset coco --config faster_rcnn_r50_fpn_1x_coco`, because coco has person in classes
# Donwload by mim download mmdet --config faster_rcnn_r50_fpn_1x_coco --dest ckpt/

# Found by `mim search mmpose  --dataset coco-wholebody --sort face_ap`
# Donwload by `mim download mmpose --config topdown_heatmap_hrnet_w48_coco_wholebody_384x288_dark_plus  --dest ckpt/`

det_config: ckpt/faster_rcnn_r50_fpn_1x_coco.py
det_ckpt:   ckpt/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth

pose_config: ckpt/topdown_heatmap_hrnet_w48_coco_wholebody_384x288_dark_plus.py
pose_ckpt:   ckpt/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth

kps: 68